# console.env with the following values is required:
# OC_URL
# OC_PASS
# OC_USER
# OC_PLUGIN_NAME
version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - console
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:console

  console:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.console
    env_file: console.env
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "oc", "status"]
        interval: 30s
        timeout: 10s
        retries: 5