# console.env with the following values is required:
# OC_URL
# OC_USER
# OC_PASS
# OC_PLUGIN_NAME
version: '3.8'
services:
  plugin:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.plugin
    depends_on:
      - console
      - x11-bridge
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:console
    environment:
      DISPLAY: ":14"
      LIBGL_ALWAYS_INDIRECT: 0
    volumes_from:
      - x11-bridge:rw

  console:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.console
    env_file: console.env
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "oc", "status"]
        interval: 60s
        timeout: 10s
        retries: 5

  x11-bridge: # https://github.com/JAremko/docker-x11-bridge
    image: jare/x11-bridge
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    ports:
      - "8080:8080"
    restart: always
    environment:
      MODE: tcp
      XPRA_HTML: "yes"
      DISPLAY: ":14"
      XPRA_TCP_PORT: "8080"
      XPRA_PASSWORD: MUST_BE_SOMETHING # This password can be anything you want